on:
  workflow_dispatch:

name: Pre-process data

jobs:
  timed_action:
    name: Process current TEMPEST data
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: rocker/tidyverse:4.2
    permissions:
      contents: write

    steps:
      - run: git config --system --add safe.directory '*'

      - name: Hello
        run: echo "Hello world!"

      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Load dropbox token
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.DROPBOX }}
          filename: "tokenfile.RDS"

      - name: Install rdrop2
        run: Rscript -e "devtools::install_github('COMPASS-DOE/rdrop2refreshtoken')"

      - name: Use R
        run: Rscript --verbose my-script.R

      - name: Commit and push
        run: |
          git config --global user.name 'stephpenn1'
          git config --global user.email 'stephanie.pennington@pnnl.gov'
          git add .
          git commit -m "Automated update" || echo "No changes to commit"
          git push
